// Copyright (c) 2026 Gembit Soultan Shirazi <gembit.soultan@gmail.com>. All rights reserved.

package seclang

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/gsoultan/gwaf/rules"
	"github.com/gsoultan/gwaf/types"
)

// Generate renders an imported ruleset as Go source.
//
// # Why emit source rather than load the .conf at runtime
//
// Because the point of migrating is to stop having a second configuration
// language. A ruleset that is Go is a ruleset the compiler checks, `git diff`
// explains, code review reads, and `gwaf lint` costs — and a typo in a target
// name is a build failure rather than a rule that silently never fires at three
// in the morning. That is the "typed, compile-checked config" axis in
// CLAUDE.md §1, and it is the one thing a SecLang file can never be.
//
// It also makes the migration *reviewable*. The generated file is a diff
// somebody can read against the CRS release it came from, and every directive
// that did not survive is a comment in it rather than a line in a log nobody
// kept.
//
// # What the output depends on
//
// Rules using @rx call seclang.MustRegex, so a converted ruleset keeps this
// module. That dependency is honest: running CRS means running its regexes, and
// a regex needs an engine. Rules that converted to literal operators depend only
// on the core module, and a caller who converts and then hand-edits away the
// last regex can drop the import entirely.
func Generate(pkg string, set rules.Set, rep Report) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by gwaf-seclang. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Converted from SecLang. Review this diff against the release it came\n")
	b.WriteString("// from: everything the converter could not translate faithfully is listed\n")
	b.WriteString("// at the bottom of this file rather than dropped silently.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// %d directives → %d rules (%d prefiltered, %d not translated).\n",
		rep.Directives, rep.Rules, rep.Prefiltered, len(rep.Skipped))
	b.WriteString("\npackage " + pkg + "\n\n")

	needsSeclang := false
	for _, r := range set {
		if _, ok := r.Op.(*regexOperator); ok {
			needsSeclang = true
			break
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/gsoultan/gwaf/rules\"\n")
	if hasLiteralOp(set) {
		b.WriteString("\t\"github.com/gsoultan/gwaf/rules/op\"\n")
	}
	if hasTransforms(set) {
		b.WriteString("\t\"github.com/gsoultan/gwaf/rules/transform\"\n")
	}
	b.WriteString("\t\"github.com/gsoultan/gwaf/types\"\n")
	for _, imp := range detectorImports(set) {
		b.WriteString("\t\"" + imp + "\"\n")
	}
	if needsSeclang {
		b.WriteString("\t\"github.com/gsoultan/gwaf/seclang\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("// Ruleset returns the converted rules.\n")
	b.WriteString("//\n")
	b.WriteString("// Confidence was assigned at conversion time and is a *claim*, not a\n")
	b.WriteString("// measurement: a SecLang rule arrives with a severity and a paranoia level\n")
	b.WriteString("// and no false-positive rate. Run `gwaf calibrate` against your own traffic\n")
	b.WriteString("// before trusting the tier.\n")
	b.WriteString("func Ruleset() rules.Set {\n\treturn rules.Set{\n")

	for i := range set {
		if err := writeRule(&b, &set[i]); err != nil {
			return nil, err
		}
	}
	b.WriteString("\t}\n}\n")

	if len(rep.Skipped) > 0 {
		b.WriteString("\n// Not translated. Each of these was reported rather than approximated,\n")
		b.WriteString("// because a silently weakened rule is worse than an absent one: the\n")
		b.WriteString("// operator believes they still have it.\n//\n")
		for _, s := range rep.Skipped {
			fmt.Fprintf(&b, "//\t%s\n", s)
		}
	}
	// Formatted rather than emitted raw. It orders the imports and aligns the
	// fields, and -- more usefully -- it *fails* on invalid Go, so a converter
	// bug becomes an error here instead of a build failure in somebody else's
	// repository with a generated file they did not write.
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("seclang: generated source is not valid Go: %w", err)
	}
	return out, nil
}

func writeRule(b *strings.Builder, r *rules.Rule) error {
	op, err := renderOperator(r.Op)
	if err != nil {
		return fmt.Errorf("rule %d: %w", r.ID, err)
	}

	b.WriteString("\t\t{\n")
	fmt.Fprintf(b, "\t\t\tID:      %d,\n", r.ID)
	fmt.Fprintf(b, "\t\t\tPhase:   types.%s,\n", phaseConst(r.Phase))

	b.WriteString("\t\t\tTargets: []types.Target{")
	for i, t := range r.Targets {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "{Kind: types.%s", t.Kind.ConstName())
		if t.Name != "" {
			fmt.Fprintf(b, ", Name: %s", strconv.Quote(t.Name))
		}
		b.WriteString("}")
	}
	b.WriteString("},\n")

	if len(r.Transforms) > 0 {
		b.WriteString("\t\t\tTransforms: []rules.Transform{")
		for i, t := range r.Transforms {
			if i > 0 {
				b.WriteString(", ")
			}
			n, ok := transformConst(t.Name())
			if !ok {
				return fmt.Errorf("rule %d: transform %q has no exported name", r.ID, t.Name())
			}
			b.WriteString("transform." + n)
		}
		b.WriteString("},\n")
	}

	fmt.Fprintf(b, "\t\t\tOp:         %s,\n", op)
	fmt.Fprintf(b, "\t\t\tActions:    []rules.Action{%s},\n", actionExpr(r.Actions))
	fmt.Fprintf(b, "\t\t\tSeverity:   types.%s,\n", severityConst(r.Severity))
	fmt.Fprintf(b, "\t\t\tConfidence: types.%s,\n", confidenceConst(r.Confidence))
	fmt.Fprintf(b, "\t\t\tMsg:        %s,\n", strconv.Quote(r.Msg))
	if len(r.Tags) > 0 {
		b.WriteString("\t\t\tTags:       []string{")
		for i, t := range r.Tags {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(t))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	return nil
}

// renderOperator turns an operator back into the expression that builds it.
//
// A converter that could not do this would be emitting code that does not
// compile, so an operator with no rendering is an error rather than a silent
// omission — the same rule the whole package follows.
func renderOperator(o rules.Operator) (string, error) {
	switch v := o.(type) {
	case *regexOperator:
		return "seclang.MustRegex(" + strconv.Quote(v.Pattern()) + ")", nil
	}

	// Literal operators are rendered from their declared literals, which is
	// exactly what they were constructed from.
	lits, required := o.Literals()
	switch o.Name() {
	case "contains":
		if len(lits) == 1 {
			return "op.Contains(" + strconv.Quote(lits[0]) + ")", nil
		}
	case "contains_any":
		if required && len(lits) > 0 {
			return "op.ContainsAny(" + quoteList(lits) + ")", nil
		}
	case "equals":
		if len(lits) == 1 {
			return "op.Equals(" + strconv.Quote(lits[0]) + ")", nil
		}
	case "has_prefix":
		if len(lits) == 1 {
			return "op.HasPrefix(" + strconv.Quote(lits[0]) + ")", nil
		}
	case "detect_sqli":
		return "sqli.Operator()", nil
	case "detect_xss":
		return "xss.Operator()", nil
	}
	return "", fmt.Errorf("operator %q cannot be rendered as source", o.Name())
}

func quoteList(ss []string) string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = strconv.Quote(s)
	}
	return strings.Join(out, ", ")
}

// detectorImports returns the detector packages the generated rules reference.
//
// @detectSQLi and @detectXSS map onto gwaf's structural detectors, which is the
// one place the translation is an upgrade rather than a port -- so the generated
// file has to import them.
func detectorImports(set rules.Set) []string {
	seen := map[string]bool{}
	for i := range set {
		switch set[i].Op.Name() {
		case "detect_sqli":
			seen["github.com/gsoultan/gwaf/detect/sqli"] = true
		case "detect_xss":
			seen["github.com/gsoultan/gwaf/detect/xss"] = true
		}
	}
	out := make([]string, 0, len(seen))
	for k := range seen {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func hasLiteralOp(set rules.Set) bool {
	for i := range set {
		switch set[i].Op.Name() {
		case "contains", "contains_any", "equals", "has_prefix":
			return true
		}
	}
	return false
}

func hasTransforms(set rules.Set) bool {
	for i := range set {
		if len(set[i].Transforms) > 0 {
			return true
		}
	}
	return false
}

func phaseConst(p types.Phase) string {
	switch p {
	case types.PhaseRequestHeaders:
		return "PhaseRequestHeaders"
	case types.PhaseRequestBody:
		return "PhaseRequestBody"
	case types.PhaseResponseHeaders:
		return "PhaseResponseHeaders"
	case types.PhaseResponseBody:
		return "PhaseResponseBody"
	default:
		return "PhaseRequestBody"
	}
}

func transformConst(name string) (string, bool) {
	switch name {
	case "url_decode":
		return "URLDecode", true
	case "lowercase":
		return "Lowercase", true
	case "remove_whitespace":
		return "RemoveWhitespace", true
	case "compress_whitespace":
		return "CompressWhitespace", true
	case "normalize_path":
		return "NormalizePath", true
	}
	return "", false
}

func severityConst(s types.Severity) string {
	switch s {
	case types.SeverityCritical:
		return "SeverityCritical"
	case types.SeverityError:
		return "SeverityError"
	case types.SeverityWarning:
		return "SeverityWarning"
	default:
		return "SeverityNotice"
	}
}

func confidenceConst(c types.Confidence) string {
	switch c {
	case types.Certain:
		return "Certain"
	case types.High:
		return "High"
	case types.Medium:
		return "Medium"
	case types.Low:
		return "Low"
	default:
		return "Heuristic"
	}
}

func actionExpr(as []rules.Action) string {
	if len(as) == 0 {
		return "rules.Score"
	}
	out := make([]string, 0, len(as))
	for _, a := range as {
		switch a.Name() {
		case "block":
			out = append(out, "rules.Block")
		case "allow":
			out = append(out, "rules.Allow")
		case "log":
			out = append(out, "rules.Log")
		default:
			out = append(out, "rules.Score")
		}
	}
	sort.Strings(out)
	return strings.Join(out, ", ")
}
